# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: MPL-2.0
---
- name: Create afterdbus.conf
  copy:
    src: files/etc/systemd/system/vmtoolsd.service.d/afterdbus.conf
    dest: /etc/systemd/system/vmtoolsd.service.d/afterdbus.conf
    mode: 0644

- name: Disable DHCP on the network interface
  file:
    path: "/etc/systemd/network/99-dhcp-en.network"
    state: absent

- import_tasks: va_hardening.yml
  when: photon3_stig_compliance != "true"

- name: Enable Apparmor service
  systemd:
    name: apparmor
    daemon_reload: yes
    enabled: true
    state: restarted

- name: Enable Apparmor in kernel
  replace:
    path: /boot/photon.cfg
    regexp: "apparmor=0"
    replace: "apparmor=1"

- name: Enable POS flag in kernel
  lineinfile:
    path: /boot/photon.cfg
    backrefs: yes
    regexp: "^(?!.*pos=1)(photon_cmdline.*)"
    line: '\1 pos=1'
